# This CI job installs Crystal and shard dependencies, then executes `crystal spec` to run the test suite
# More configuration options are available at https://crystal-lang.github.io/install-crystal/configurator.html

on:
  release:
    types: [created]
jobs:
  release:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        k8s:
          - "v1.11"
          - "v1.12"
          - "v1.13"
          - "v1.14"
          - "v1.15"
          - "v1.16"
          - "v1.17"
          - "v1.18"
          - "v1.19"
          - "v1.20"
          - "v1.21"
          - "v1.22"
          - "v1.23"
          - "v1.24"
          - "v1.25"
          - "v1.26"
          - "v1.27"
        os:
          - ubuntu-latest
          - macos-latest
        crystal:
          - latest
          - 1.3
          - 1.4
          - 1.5
          - 1.6
          - 1.7
          - 1.8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: rinx/setup-k3d@v0.0.4
        with:
          skipClusterCreation: true

      - name: Setup k3s cluster
        run: k3d cluster create -c ./spec/files/k3d/${{ matrix.k8s }}.yml
      - name: Write kubeconfig
        run: k3d kubeconfig get k3d-cluster-test > ./spec/files/kube_config_test.yml

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards update --ignore-crystal-version

      - name: Run tests
        run: crystal spec --exclude-warnings $(crystal env CRYSTAL_LIBRARY_PATH) --exclude-warnings ./lib/ --error-trace -Dk8s_${{ matrix.k8s }}
        timeout-minutes: 30
      - name: Tear down cluster
        run: k3d cluster delete k3d-cluster-test
